services:
  api:
    build:
      context: .
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - MONGO_URI=mongodb://mongo:27017/imageapp
      - JWT_SECRET=12345
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
